### ISSUE TITLE
생성할 Entity 내용

### ISSUE THREAD

**Issue by crystalvalley** [crystalvalley/TeamProject#1]
[Entity 내용 링크 ](https://docs.google.com/spreadsheets/d/1olhHkxYJGa0zRVMqk5WgDnp8vuxKwcgNVrR0LoVa5RE/edit#gid=0)

**Comment by Minju01** [comment]
[공유 테이블]
sharId,
sequence,
sharUser

sharId = 공유한 사람 아이디,
sequence = 시퀀스
sharUser= 공유대상

**Comment by vzb13** [comment]
-Room테이블
sequence,
content

-Room Member 테이블
sequence(foreign key로),
userid

**Comment by Minju01** [comment]
[감정표현 테이블]
sequence = 시퀀스(pk),
userid = 사용한사람 유저아이디(외래키),
emotionType = 감정표현

**Comment by vzb13** [comment]
-댓글테이블
sequence,
userid,
sharedcontent

**Comment by Minju01** [comment]
[음성 사진 테이블]
sound ,
url,
type ,
sequence([fk)

**Comment by vzb13** [comment]
-즐겨찾기 테이블
userid,
boardsequence,
uploaddate

**Comment by Minju01** [comment]
[카드 테이블]
day = 작성날짜,
id = 작성자,
conteast = 내용,
sound = 음성,
image = 사진,
userid = 받는사람,
sequence =

**Comment by crystalvalley** [comment]
[댓글]
day default sysdate,
id,
content,
sound,
sequence,
parent,
depth,
order

**Comment by Minju01** [comment]
Favorites 의 게시글 oneToOne 에서 manyToOne으로 수정했습니다 보더쪽에 양방향으로 수정해야 합니다

**Comment by Minju01** [comment]
Share 의 targetMember 양방향관계 추가 됬습니다 Member 부분에 양방향 관계 만들어주세요

**Comment by Minju01** [comment]
데이터베이스 테이블 작성한 사진에 공유한게시글부분에 회원 targetMember //공유받은사람 ,sharedMember// 공유대상 추가해야 합니다

**Comment by Minju01** [comment]
Sound 의 게시글에 ManyToOne 관계 추가됬습니다 . 보더에  oneToMany Sounder  관계 추가 부탁드립니다. 
Reply에 OneToMany replySound 관계 추가 부탁드립니다 .   Card에 OneToMany CardSound 관계 추가 부탁드립니다

**Comment by Minju01** [comment]
GroupMember 테이블 새로 만들었습니다 member의 member OneToMany 양방향 관계 만들어주세요.
Group 의 OneToMany Groupmember 관계 만들어주세요
