### ISSUE TITLE
Boards Table에서 Authority type을 정해야 할 것 같습니다. 

### ISSUE THREAD

**Issue by sa82trip** [crystalvalley/TeamProject#17]
일단 제 생각으로는

1. 자기자신만
2. 친구만
3. 팔로워만
4. 전체공개

이렇게 생각했는데, 다른 분들 의견 종합해서 반영했으면 하니 의견 적어주세요~

**Comment by crystalvalley** [comment]
그거면 될 거 같습니다.
단일 대상한테 보내는 건 카드가 있으니... 용도는 다르지만

**Comment by sa82trip** [comment]
@crystalvalley  알겠습니다. 그럼 이대로 진행하겠습니다.
